version: '3'

services:
  fastapi:
    build: ./
    image: myimage
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    restart: unless-stopped
    volumes:
      - cache:/data

volumes:
  cache:
    driver: local
